#!/usr/bin/python

###############################################################################
# A script to print all jobs for the current user                             #
###############################################################################

### Import modules ###
import subprocess
import re

### Set server information ###
ServTag = "vpbs1"

### Find username ###
MyUName = subprocess.check_output('whoami')
MyUName = MyUName.strip()

### Print a blank line ###
print("")

### Call qstat ###
jobcmd = "qstat -u "+MyUName
JobOut = subprocess.check_output(jobcmd,shell=True)

### Alter qstat output ###
JobOut = JobOut.strip()
JobOut = JobOut.split('\n')
for line in JobOut:
  if (line.strip() != (ServTag+':')):
    line = re.sub(r'\.vpbs1 ',r' ',line)
    line = re.sub(r'Job ID         ',r'Job ID   ',line)
    line = re.sub(r'---------------',r'---------',line)
    line = re.sub(r'              Req',r'        Req',line)
    print(line)

### Clean up and exit ###
print("")
