#!/usr/bin/env python

###############################################################################
# A script to print all jobs for the current user                             #
###############################################################################

#NB: Python 2.7 or higher is required.

### Import modules ###
import subprocess
import re

### Set server information ###
ServTag = "vpbs2.g" #Tag at the end of job id (e.g. 42424242.vpbs1)

### Find username ###
MyUName = subprocess.check_output('whoami')
MyUName = MyUName.decode('utf-8').strip() #Remove white space

### Clear screen ###
subprocess.call('clear') #Only prints blank lines

### Print a blank line ###
print("")

### Call qstat ###
jobcmd = "qstat -u "+MyUName
JobOut = subprocess.check_output(jobcmd,shell=True).decode('utf-8')

### Fix alignment ###
ServRep = "  "
servdifflen = abs(len(ServTag)-6)
for i in range(servdifflen):
  ServRep += " "

### Alter qstat output ###
JobOut = JobOut.strip() #White space from ends
JobOut = JobOut.split('\n') #Separate lines
for line in JobOut:
  if (line.strip() != (ServTag+':')):
    line = re.sub((r'\.'+ServTag+' '),(r''+ServRep),line)
    line = re.sub(r'Job ID         ',r'Job ID   ',line)
    line = re.sub(r'---------------',r'---------',line)
    line = re.sub(r'              Req',r'        Req',line)
    print(line)

### Clean up and exit ###
print("")
exit(0)
