#!/bin/bash

#A simple script to produce a constantly updating queue t.o.p.
#This is a simplified and specialized version of pbstop

#Usage: Qtop -q [ queue name ]
#Usage: Qtop -u [ username ]
#Usage: Qtop -r [ username ]

#Define sed command for known usernames
UsersedLine=""
#Add usernames (first one should not have a ; character
UsersedLine=${UsersedLine}"s/ft0805/Kratz /g"
UsersedLine=${UsersedLine}";s/fc1875/Hedi  /g"
UsersedLine=${UsersedLine}";s/ee4522/Andres/g"
UsersedLine=${UsersedLine}";s/fg3012/Alice /g"
UsersedLine=${UsersedLine}";s/fj9636/Tu    /g"
UsersedLine=${UsersedLine}";s/fc3161/Bishnu/g"
UsersedLine=${UsersedLine}";s/fh0764/Pascal/g"
UsersedLine=${UsersedLine}";s/fn9787/Joseph/g"
UsersedLine=${UsersedLine}";s/at8036 /Aragorn/g"
UsersedLine=${UsersedLine}";s/es4448/Pavel /g"
#Add server tag
UsersedLine=${UsersedLine}";s/\.vpbs1//g"

#Help mode
if [[ "$1" == *"-h"* ]]; then
  echo ""
  echo "A simple script to produce a constantly updating queue t.o.p."
  echo ""
  echo "Usage: Qtop -q [ queue name ]"
  echo "Usage: Qtop -r [ username ]"
  echo "Usage: Qtop -u [ username ]"
  echo "Usage: Qtop -u me"
  echo ""
  echo ""
  echo "  -q  Show active and queued jobs for a queue"
  echo ""
  echo "  -u  Show active and queued jobs for a user. Jobs for the"
  echo "      current user can be shown with the '-u me' command."
  echo ""
  echo "  -r  Show only active jobs for a user."
  echo ""
  echo "The script runs until the user presses 'q'"
  echo ""
  echo "Note: Behavior when refreshing the screen is terminal dependent."
  echo ""
  exit
fi

#User mode
if [[ "$1" == *"-u"* ]]; then
  QtopUser=$2
  if [[ $2 == "me" ]]; then
    QtopUser=$(whoami)
  fi
  #Infinite loop, escape with Ctrl-C or by typing the letter q
  keypress=""
  while [ 0 -lt 1 ]
  do
    #Clear the screen
    #NB: 3 different types are included since the commands are
    # terminal dependent
    clear
    reset
    echo -en "\e[3J"
    #Print title
    echo ""
    echo "Active and queued jobs for user ${QtopUser}:"
    #Print qstat titles that are lost in grep/sed
    echo "                                                      Req'd  Req'd   Elap"
    echo "Job ID    Username Queue    Jobname    SessID NDS TSK Memory Time  S Time"
    echo "--------- -------- -------- ---------- ------ --- --- ------ ----- - -----"
    #Find and replace usernames using the variables above
    qstat -u ${QtopUser} | grep -e "${QtopUser}" | sed "${UsersedLine}"
    #Wait for 30 seconds before looping
    sleep 2.0
    for i in {1..15}
    do
      sleep 1.0
      read -t 1 -n 1 keypress
      if [[ "${keypress}" == *"q"* ]]; then
        echo ""
        exit
      fi
    done
  done
fi

#Running mode
if [[ "$1" == *"-r"* ]]; then
  QtopUser=$2
  if [[ $2 == "me" ]]; then
    QtopUser=$(whoami)
  fi
  #Infinite loop, escape with Ctrl-C or by typing the letter q
  keypress=""
  while [ 0 -lt 1 ]
  do
    #Clear the screen
    #NB: 3 different types are included since the commands are
    # terminal dependent
    clear
    reset
    echo -en "\e[3J"
    #Print title
    echo ""
    echo "Active jobs for user ${QtopUser}:"
    #Print qstat titles that are lost in grep/sed
    echo "                                                      Req'd  Req'd   Elap"
    echo "Job ID    Username Queue    Jobname    SessID NDS TSK Memory Time  S Time"
    echo "--------- -------- -------- ---------- ------ --- --- ------ ----- - -----"
    #Find and replace usernames of running jobs using the variables above
    qstat -u ${QtopUser} | grep -e "${QtopUser}" \
    | grep -e " R " | sed "${UsersedLine}"
    #Wait for 30 seconds before looping
    sleep 2.0
    for i in {1..15}
    do
      sleep 1.0
      read -t 1 -n 1 keypress
      if [[ "${keypress}" == *"q"* ]]; then
        echo ""
        exit
      fi
    done
  done
fi

#Queue mode
if [[ "$1" == *"-q"* ]]; then
  #Infinite loop, escape with Ctrl-C or by typing the letter q
  keypress=""
  while [ 0 -lt 1 ]
  do
    #Clear the screen
    #NB: 3 different types are included since the commands are
    # terminal dependent
    clear
    reset
    echo -en "\e[3J"
    #Print basic info
    echo ""
    qstat -Q $2
    echo ""
    echo "Active and queued jobs on ${2}:"
    #Print qstat titles that are lost in grep/sed
    echo "                                                      Req'd  Req'd   Elap"
    echo "Job ID    Username Queue    Jobname    SessID NDS TSK Memory Time  S Time"
    echo "--------- -------- -------- ---------- ------ --- --- ------ ----- - -----"
    #Find and replace usernames using the variables above
    qstat -a | grep -e "$2" | sed "${UsersedLine}"
    #Wait for 30 seconds before looping
    sleep 2.0
    for i in {1..15}
    do
      sleep 1.0
      read -t 1 -n 1 keypress
      if [[ "${keypress}" == *"q"* ]]; then
        echo ""
        exit
      fi
    done
  done
fi

echo ""
echo "Usage: Qtop -q [ queue name ]"
echo "Usage: Qtop -u [ username name ]"
echo "Usage: Qtop -r [ username name ]"
echo ""
echo "Use -h for more detailed help."
exit
