#!/bin/python

###############################################################################
# A simple script to produce a constantly updating queue t.o.p.               #
# This is a simplified and specialized version of pbstop                      #
###############################################################################

#Usage: Qtop -q [ queue name ]
#Usage: Qtop -u [ username ]
#Usage: Qtop -r [ username ]

### Import modules ###
import os
import re

### Read list of usernames from the file defined in ${QtopUsers} ###


### Read arguments ###


### Semi-infinite loop ###


### Exit if no valid input was found ###
