#!/bin/bash

#Script to print the username, server, and path for scp or rsync

#Set server name
server=grid.wayne.edu

#Help mode
if [[ "$1" == *"-h"* ]]; then
  echo ""
  echo "Prints the path to a directory and/or file in the working directory."
  echo "The path includes the username and server for scp or rsync"
  echo ""
  echo "Usage:"
  echo "       SCPpath"
  echo "       SCPpath <directory>"
  echo "       SCPpath <directory/filemame>"
  echo ""
  exit
fi

#Print path
scpuser=$(whoami)
dirpath=$(pwd)
fullpath=${scpuser}@${server}:${dirpath}
fullpath=${fullpath}/${1}
echo ${fullpath}
